-- script 1.2.6

ALTER TABLE PROSPECT_SALES_ACTION ADD CHANGE_DATE TIMESTAMP DEFAULT NULL;

ALTER TABLE PROSPECT_SALES_ACTION ADD CREATION_DATE TIMESTAMP DEFAULT NULL;

ALTER TABLE PROSPECT_SALES_ACTION ADD CHANGED_BY_USER_ID NUMERIC(9,0) DEFAULT NULL;