ALTER TABLE PROSPECT_SALES_ACTION ADD CHANGE_DATE TIMESTAMP DEFAULT NULL;

ALTER TABLE PROSPECT_SALES_ACTION ADD CREATION_DATE TIMESTAMP DEFAULT NULL;

ALTER TABLE PROSPECT_SALES_ACTION ADD CHANGED_BY_USER_ID NUMERIC(9,0) DEFAULT NULL;

-- this is a dup, it is in 1.2.0---
ALTER TABLE NOTE ADD TEMP_NOTE VARCHAR(500);
UPDATE NOTE SET TEMP_NOTE = NOTE;
ALTER TABLE NOTE DROP COLUMN NOTE;
ALTER TABLE NOTE ADD NOTE VARCHAR(2000);
UPDATE NOTE SET NOTE = TEMP_NOTE;
ALTER TABLE NOTE DROP COLUMN TEMP_NOTE;

--- missing update scripts ----

alter table campaign add column DESCRIPTION CHARACTER VARYING(200);
alter table prospect add column TERRITORY_ASSIGNED_ON_CREATION NUMERIC(9,0) ;