-- USED FOR PROSPECT ID FROM EXTERNAL SYSTEM --
ALTER TABLE PROSPECT
	ADD EXTERNAL_ID VARCHAR(25);
	
ALTER TABLE DOCUMENT
	ADD EXTERNAL_ID VARCHAR(25);	

alter table prospect add temp_phone varchar(30);
update  prospect set temp_phone = phone_ext;
alter table prospect drop column phone_ext;
alter table prospect add phone_ext varchar(30);
update  prospect set phone_ext = temp_phone;
alter table prospect drop column temp_phone;


--mikes changes
CREATE TABLE USER_TERRITORIES  (
	USER_TERRITORY_ID NUMERIC(9,0) NOT NULL,
	TERRITORY_ID NUMERIC(9,0) NOT NULL, 
	USER_ID NUMERIC(9,0) NOT NULL,  
	CONSTRAINT PROS_TERR_01 PRIMARY KEY(USER_TERRITORY_ID)); 	


CREATE TABLE USER_STATUSES  (
	USER_STATUS_ID NUMERIC(9,0) NOT NULL,
	STATUS_ID NUMERIC(9,0) NOT NULL, 
	USER_ID NUMERIC(9,0) NOT NULL,  
	CONSTRAINT PROS_STATUS_01 PRIMARY KEY(USER_STATUS_ID)); 	


ALTER TABLE TERRITORY ADD COLUMN RETURN_TERRITORY_ID NUMERIC(9,0);
ALTER TABLE TERRITORY ADD COLUMN RETURN_TIME NUMERIC(9,0);

ALTER TABLE PROSPECT ADD COLUMN TERRITORY_CHANGED_DATE TIMESTAMP DEFAULT NULL;

CREATE TABLE TERRITORY_CHANGE (
	TERRITORY_CHANGE_ID NUMERIC(9,0) NOT NULL,
	ORIGINAL_TERRITORY_ID NUMERIC(9,0),
	NEW_TERRITORY_ID NUMERIC(9,0) NOT NULL,
	USER_ID NUMERIC(9,0) NOT NULL,
	CHANGE_DATE TIMESTAMP NOT NULL,
	CONSTRAINT TERR_CHAN_01 PRIMARY KEY(TERRITORY_CHANGE_ID)); 


ALTER TABLE TERRITORY_CHANGE ADD COLUMN AUTO_TERRITORY_CHANGE NUMERIC(9,0);

ALTER TABLE TERRITORY ADD COLUMN RANDOM_SEQUENCE NUMERIC(9,0);
ALTER TABLE TERRITORY ADD COLUMN MAX_PROSPECT_DISPLAY NUMERIC(9,0);

ALTER TABLE WEBUSER ADD COLUMN SPECIFIC_TERRITORIES NUMERIC(9,0);
ALTER TABLE WEBUSER ADD COLUMN SPECIFIC_STATUSES NUMERIC(9,0);

ALTER TABLE TERRITORY ADD COLUMN INCLUDE_IN_CONVERSION_REPORT NUMERIC(9,0);
ALTER TABLE PROSPECT ADD COLUMN ACTIVITY_DATE TIMESTAMP;

ALTER TABLE WEBUSER ADD COLUMN LIMIT_VIEW NUMERIC(9,0);
