-- data migration scripts - first half is probably already there---

--- tables--------
CREATE TABLE WEBUSER_DM ( 
	USER_NO NUMERIC(10, 0) NOT NULL , 
	ACTIVE NUMERIC(1, 0) DEFAULT NULL , 
	USER_TYPE NUMERIC(1, 0) DEFAULT NULL , 
	USER_NAME VARCHAR(30) DEFAULT NULL , 
	PASSWORD VARCHAR(20) DEFAULT NULL , 
	DEFAULT_CONVERSION_CLASS VARCHAR(50) DEFAULT NULL ,
	CONSTRAINT USER_01_DM PRIMARY KEY( USER_NO ) ) ; 
	
CREATE TABLE EDI_GROUP ( 
	EDI_GROUP_ID NUMERIC(11, 0) NOT NULL , 
	UPLOADED_BY VARCHAR(50) DEFAULT NULL , 
	UPLOAD_DATE TIMESTAMP DEFAULT NULL , 
	FILENAME VARCHAR(255) DEFAULT NULL , 
	DOWNLOADED NUMERIC(1,0) DEFAULT NULL ,
	DOWNLOADED_BY VARCHAR(50) DEFAULT NULL , 
	DOWNLOAD_DATE TIMESTAMP DEFAULT NULL ,
	ORDER_LIST VARCHAR(255) DEFAULT NULL ,
	CONSTRAINT EDI_GRP_01 PRIMARY KEY( EDI_GROUP_ID ) ) ; 	
	
CREATE TABLE EDI_HEADER ( 
	EDI_HEADER_ID NUMERIC(11, 0) NOT NULL , 
	EDI_GROUP_ID NUMERIC(11, 0) NOT NULL , 
	EDI_HEADER_CONTENT VARCHAR(250) DEFAULT NULL , 
	CONSTRAINT EDI_HEAD_01 PRIMARY KEY( EDI_HEADER_ID ) ) ; 		
	
CREATE TABLE EDI_DETAIL ( 
	EDI_DETAIL_ID NUMERIC(11, 0) NOT NULL , 
	EDI_HEADER_ID NUMERIC(11, 0) NOT NULL , 
	EDI_DETAIL_CONTENT VARCHAR(150) DEFAULT NULL , 
	CONSTRAINT EDI_DET_01 PRIMARY KEY( EDI_DETAIL_ID ) ) ; 	
	
-- ADD INTERCHANGE AND GROUP CONTROL ID TABLES --
CREATE TABLE EDI_INTERCHANGE_CONTROL ( 
	EDI_INTERCHANGE_CONTROL_ID NUMERIC(5, 0) NOT NULL , 
	EDI_INTERCHANGE_CONTROL_NUMBER NUMERIC (9,0) ,
	CONSTRAINT EDI_INTERCHANGE_CONTROL_01 PRIMARY KEY( EDI_INTERCHANGE_CONTROL_ID ) ) ; 
	
CREATE TABLE EDI_GROUP_CONTROL ( 
	EDI_GROUP_CONTROL_ID NUMERIC(5, 0) NOT NULL , 
	EDI_GROUP_CONTROL_NUMBER NUMERIC (9,0) ,
	CONSTRAINT EDI_GROUP_CONTROL_01 PRIMARY KEY( EDI_GROUP_CONTROL_ID ) ) ; 	
			

--- indexes ----

CREATE UNIQUE INDEX USR_PK_DM 
	ON WEBUSER_DM ( USER_NO ) ; 
	
CREATE INDEX USR_USRN_IDX_DM 
	ON WEBUSER_DM ( USER_NAME ) ; 	
	
CREATE UNIQUE INDEX EDI_GRP_PK 
	ON EDI_GROUP ( EDI_GROUP_ID ) ; 	
	
CREATE INDEX EDI_GRP_UPLDT_IDX 
	ON EDI_GROUP ( UPLOAD_DATE ) ; 		
	
CREATE INDEX EDI_GRP_DWN_IDX 
	ON EDI_GROUP ( DOWNLOADED ) ; 			
	
CREATE UNIQUE INDEX EDI_HEAD_PK 
	ON EDI_HEADER ( EDI_HEADER_ID ) ; 		
	
CREATE INDEX EDI_HEAD_GRP_IDX 
	ON EDI_HEADER ( EDI_GROUP_ID ) ; 		
	
CREATE UNIQUE INDEX EDI_DET_PK 
	ON EDI_DETAIL ( EDI_DETAIL_ID ) ; 				
	
CREATE INDEX EDI_DET_HEAD_IDX 
	ON EDI_DETAIL ( EDI_HEADER_ID ) ; 					
	
	
	
--- alter scripts -----

ALTER TABLE EDI_HEADER  
	ADD CONSTRAINT EDI_HEAD_02 
	FOREIGN KEY( EDI_GROUP_ID ) 
	REFERENCES EDI_GROUP ( EDI_GROUP_ID ) 
	ON DELETE CASCADE 
	ON UPDATE RESTRICT ;
	
ALTER TABLE EDI_DETAIL  
	ADD CONSTRAINT EDI_DET_02 
	FOREIGN KEY( EDI_DETAIL_ID ) 
	REFERENCES EDI_DETAIL ( EDI_DETAIL_ID ) 
	ON DELETE CASCADE 
	ON UPDATE RESTRICT ; 
	 
	insert into edi_group_control values(1,1000);
	insert into edi_interchange_control values(1,100000000);
	 
	 -- insert in admin user --

insert into webuser_dm (user_no, active, user_type, user_name, password) values (1,1,3,'admin','admin');
-- migration log---

--- 1/30/09 automated email ---


CREATE TABLE email_sales_action ( 
	email_action_id NUMERIC(9,0) NOT NULL , 
	email_action_description VARCHAR(100) NOT NULL , 
	email_draft_to_use NUMERIC(9,0) NOT NULL , 
	verified_yes_no NUMERIC(1,0), 
	use_salesman_from_email NUMERIC(1,0) , 
	creation_date TIMESTAMP,
	send_email_date TIMESTAMP,
	actual_email_date TIMESTAMP,
	CONSTRAINT email_sales_action_01 PRIMARY KEY( email_action_id ) ) ; 

CREATE TABLE email_sales_action_sent_prospects ( 
	sent_email_action_id NUMERIC(9,0), 
	email_action_id NUMERIC(9,0), 
	prospect_id numeric(10),
	sent_date TIMESTAMP,
	CONSTRAINT sent_email_action_01 PRIMARY KEY( sent_email_action_id ) ) ; 

CREATE TABLE email_sales_action_statuses  (
	email_status_id NUMERIC(9,0) NOT NULL,
	email_action_id NUMERIC(9,0) NOT NULL , 
	status_id NUMERIC(9,0) NOT NULL, 
	CONSTRAINT email_status_01 PRIMARY KEY(email_status_id)); 

CREATE TABLE email_sales_action_lobs  (
	email_lob_id NUMERIC(9,0) NOT NULL,
	email_action_id NUMERIC(9,0) NOT NULL , 
	lob_id NUMERIC(9,0) NOT NULL, 
	CONSTRAINT email_lob_01 PRIMARY KEY(email_lob_id)); 
	
CREATE TABLE email_sales_action_territories  (
	email_territory_id NUMERIC(9,0) NOT NULL,
	email_action_id NUMERIC(9,0) NOT NULL , 
	territory_id NUMERIC(9,0) NOT NULL, 
	CONSTRAINT email_territory_01 PRIMARY KEY(email_territory_id)); 


CREATE TABLE EMAIL_QUEUE_AUDIT  (

	EMAIL_QUEUE_AUDIT_ID NUMERIC(9,0) NOT NULL,
	PROSPECT_ID NUMERIC(9,0) NOT NULL, 
	WEBPROFILE_ID NUMERIC(9,0) NOT NULL,  
	EMAIL_DRAFT_ID NUMERIC(9,0) NOT NULL,
	EXPORT_DATE TIMESTAMP,
	RETURN_DATE TIMESTAMP, 
	USER_ID NUMERIC(9,0),
	STATUS NUMERIC(9,0),
	FILE_NAME VARCHAR(50),

	CONSTRAINT EMAIL_QUEUE_AUDIT_01 PRIMARY KEY(EMAIL_QUEUE_AUDIT_ID)); 	
								