CREATE TABLE USER_LOBS  (
	USER_LOB_ID NUMERIC(9,0) NOT NULL,
	LOB_ID NUMERIC(9,0) NOT NULL, 
	USER_ID NUMERIC(9,0) NOT NULL,  
	CONSTRAINT USER_LOB_01 PRIMARY KEY(USER_LOB_ID)); 	
	
ALTER TABLE WEBUSER ADD COLUMN SPECIFIC_LOBS NUMERIC(9,0);
ALTER TABLE WEBUSER ADD COLUMN SPECIFIC_TERRITORIES NUMERIC(9,0);
ALTER TABLE WEBUSER ADD COLUMN SPECIFIC_STATUSES NUMERIC(9,0);


ALTER TABLE PROSPECT ADD TERRITORY_ASSIGNED_ON_CREATION NUMERIC(9,0) DEFAULT NULL;


ALTER TABLE CAMPAIGN ADD DESCRIPTION CHARACTER VARYING(200);

